name: Scheduled Build

on:
  schedule:
    # 06:00 and 18:00 Turkey time (UTC+3)
    - cron: '0 3,15 * * *'
  workflow_dispatch:

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK }}"
